# git-cliff changelog configuration
# https://git-cliff.org/docs/configuration

[remote.github]
owner = "usepictum"
repo = "pictum"

[bump]
features_always_bump_minor = false
initial_tag = "pictum-vue@v0.1.4"

[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.

This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""
body = """
{% if version %}
## {{ version | trim_start_matches(pat="pictum-vue@") }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}
## Unreleased
{% endif %}

{% for group, commits in commits | group_by(attribute="group") %}
  ### {{ group }}
  {% for commit in commits %}
    * {{ commit.message | split(pat="\n") | first | trim }} \
      ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))
  {%- endfor %}

{% endfor -%}

{% if version and previous.version %}
**Comparison**: {{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}
{% endif %}

{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""
trim = true
footer = """
<!-- generated by git-cliff -->
"""

[git]
conventional_commits = true
filter_unconventional = true
tag_pattern = '^pictum-vue@v[0-9]+\.[0-9]+\.[0-9]+(?:[-+][0-9A-Za-z.-]+)?$'
commit_parsers = [
  { sha = "51d9a6f8dcbaa06fd20a8637ac880931f73e79a6", skip = true },
  { message = '^[a-zA-Z]+(?:\([^)]+\))?!:', group = "Breaking Changes" },
  { message = '^feat(?:\([^)]+\))?:', group = "Features" },
  { message = '^fix(?:\([^)]+\))?:', group = "Bug Fixes" },
  { message = '^perf(?:\([^)]+\))?:', group = "Performance Improvements" },
  { message = '^revert(?:\([^)]+\))?:', group = "Reverts" },
]
commit_preprocessors = [{ pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" }]
filter_commits = true
include_paths = ["integrations/vue/**"]
sort_commits = "newest"
